[local]
localhost

[mongodb]
mongodb.mokridevops.shop

[redis]
redis.mokridevops.shop

[mysql]
mysql.mokridevops.shop

[rabbitmq]
rabbitmq.mokridevops.shop

[frontend]
mokridevops.shop

[catalogue]
catalogue.mokridevops.shop